import PDFDocument from "pdfkit";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import { IFlashcard } from "../models/StudyMaterial";

export type ExportFormat = "pdf" | "docx" | "md";

export interface ExportPayload {
  title: string;
  content: string;
  flashcards?: IFlashcard[];
  footer?: string;
}

interface ContentBlock {
  type: "h1" | "h2" | "h3" | "bullet" | "paragraph";
  text: string;
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-z0-9._-]/gi, "_").slice(0, 120) || "study_material";
}

function parseMarkdownBlocks(content: string): ContentBlock[] {
  const blocks: ContentBlock[] = [];
  const lines = content.split("\n");

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    if (line.startsWith("### ")) {
      blocks.push({ type: "h3", text: line.slice(4).replace(/\*\*/g, "") });
    } else if (line.startsWith("## ")) {
      blocks.push({ type: "h2", text: line.slice(3).replace(/\*\*/g, "") });
    } else if (line.startsWith("# ")) {
      blocks.push({ type: "h1", text: line.slice(2).replace(/\*\*/g, "") });
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      blocks.push({
        type: "bullet",
        text: line.replace(/^[-*]\s+/, "").replace(/\*\*/g, ""),
      });
    } else {
      blocks.push({
        type: "paragraph",
        text: line.replace(/\*\*/g, "").replace(/`/g, ""),
      });
    }
  }

  return blocks;
}

function buildBlocks(payload: ExportPayload): ContentBlock[] {
  if (payload.flashcards?.length) {
    const blocks: ContentBlock[] = [
      { type: "h2", text: "Flashcards" },
    ];
    payload.flashcards.forEach((card, i) => {
      blocks.push({ type: "h3", text: `Card ${i + 1}` });
      blocks.push({ type: "paragraph", text: `Q: ${card.question}` });
      blocks.push({ type: "paragraph", text: `A: ${card.answer}` });
    });
    return blocks;
  }
  return parseMarkdownBlocks(payload.content);
}

export function buildMarkdownExport(payload: ExportPayload): string {
  if (payload.flashcards?.length) {
    const cards = payload.flashcards
      .map(
        (c, i) =>
          `### Card ${i + 1}\n\n**Q:** ${c.question}\n\n**A:** ${c.answer}\n`
      )
      .join("\n");
    return `# ${payload.title}\n\n${cards}\n\n---\n${payload.footer || "Smart Study Companion"}`;
  }
  return `# ${payload.title}\n\n${payload.content}\n\n---\n${payload.footer || "Smart Study Companion"}`;
}

export function generatePdfBuffer(payload: ExportPayload): Promise<Buffer> {
  const blocks = buildBlocks(payload);
  const footer = payload.footer || "Generated by Smart Study Companion";

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 50,
      size: "A4",
      info: { Title: payload.title, Author: "Smart Study Companion" },
    });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(22).font("Helvetica-Bold").text(payload.title, {
      align: "left",
    });
    doc.moveDown(0.5);
    doc
      .moveTo(50, doc.y)
      .lineTo(doc.page.width - 50, doc.y)
      .strokeColor("#0d9488")
      .stroke();
    doc.moveDown(1);

    for (const block of blocks) {
      if (doc.y > doc.page.height - 80) doc.addPage();

      switch (block.type) {
        case "h1":
          doc.fontSize(18).font("Helvetica-Bold").text(block.text);
          doc.moveDown(0.4);
          break;
        case "h2":
          doc.fontSize(15).font("Helvetica-Bold").fillColor("#0f766e").text(block.text);
          doc.fillColor("#000000");
          doc.moveDown(0.35);
          break;
        case "h3":
          doc.fontSize(13).font("Helvetica-Bold").text(block.text);
          doc.moveDown(0.3);
          break;
        case "bullet":
          doc.fontSize(11).font("Helvetica").text(`• ${block.text}`, {
            indent: 12,
            lineGap: 3,
          });
          doc.moveDown(0.2);
          break;
        default:
          doc.fontSize(11).font("Helvetica").text(block.text, {
            align: "left",
            lineGap: 4,
          });
          doc.moveDown(0.35);
      }
    }

    doc.moveDown(1);
    doc
      .fontSize(9)
      .fillColor("#64748b")
      .text(footer, { align: "center" });
    doc.end();
  });
}

function headingLevel(type: ContentBlock["type"]): (typeof HeadingLevel)[keyof typeof HeadingLevel] | undefined {
  if (type === "h1") return HeadingLevel.HEADING_1;
  if (type === "h2") return HeadingLevel.HEADING_2;
  if (type === "h3") return HeadingLevel.HEADING_3;
  return undefined;
}

export async function generateDocxBuffer(payload: ExportPayload): Promise<Buffer> {
  const blocks = buildBlocks(payload);
  const footer = payload.footer || "Generated by Smart Study Companion";
  const children: Paragraph[] = [
    new Paragraph({
      text: payload.title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 240 },
    }),
  ];

  for (const block of blocks) {
    const level = headingLevel(block.type);
    if (level) {
      children.push(
        new Paragraph({
          text: block.text,
          heading: level,
          spacing: { before: 180, after: 120 },
        })
      );
    } else if (block.type === "bullet") {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: block.text })],
          bullet: { level: 0 },
          spacing: { after: 80 },
        })
      );
    } else {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: block.text })],
          spacing: { after: 120 },
        })
      );
    }
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: footer,
          italics: true,
          size: 18,
          color: "64748B",
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 },
    })
  );

  const doc = new Document({
    creator: "Smart Study Companion",
    title: payload.title,
    sections: [{ children }],
  });

  return Packer.toBuffer(doc);
}

export function getExportMime(format: ExportFormat): string {
  switch (format) {
    case "pdf":
      return "application/pdf";
    case "docx":
      return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    default:
      return "text/markdown";
  }
}

export function getExportExtension(format: ExportFormat): string {
  return format === "md" ? "md" : format;
}

export function buildExportFilename(title: string, format: ExportFormat): string {
  return `${sanitizeFilename(title)}.${getExportExtension(format)}`;
}

export async function generateExportBuffer(
  payload: ExportPayload,
  format: ExportFormat
): Promise<Buffer> {
  switch (format) {
    case "pdf":
      return generatePdfBuffer(payload);
    case "docx":
      return generateDocxBuffer(payload);
    default:
      return Buffer.from(buildMarkdownExport(payload), "utf-8");
  }
}
